project_id = "freshshift"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "https://freshshift.de"
additional_redirect_urls = [
  "https://freshshift.de/*",
  "http://localhost:3000/*",
  "http://127.0.0.1:3000/*"
]

[functions]
[functions.invite-employee]
verify_jwt = true
